### ISSUE TITLE
Convert Arduino files to C++

### ISSUE THREAD

**Issue by ivankravets** [Luos-io/Get_started#15]
Hi,

INO/PDE are invalid CPP files and are the root of bad developer experience. 

See https://docs.platformio.org/en/latest/faq/ino-to-cpp.html

**Comment by nicolas-rabault** [comment]
In the beginning, we wanted to keep the project compatible with Arduino IDE...
But the reality is that Platformio is the tool used by 100% of the people running this Get-Started. So this makes sense, thank-you @ivankravets

**Comment by ivankravets** [comment]
Ahh, I see! The problem is that Microsoft's C/C++ extension does not support INO/PDE files and they are right. It seems we should finally drop support for the INO to reduce the level of mistakes when using this "broken" format.

**Comment by nicolas-rabault** [comment]
OK, so we have to make it soon to be future-proof...

**Comment by JeromeGalan** [comment]
Fixed in luos_engine 2.6.0
